import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import App from './app/nursery';
import './app/globals.css';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './components/ui/dialog';
async function api(path:string,data?:any){const r=await fetch('/api/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر الاتصال');return d;}
function Root(){const [user,setUser]=useState<any>(null),[ready,setReady]=useState(false),[setup,setSetup]=useState(false),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[manage,setManage]=useState(false),[link,setLink]=useState(''),[users,setUsers]=useState<any[]>([]),[msg,setMsg]=useState('');const invite=new URLSearchParams(location.search).get('invite');
 async function refresh(){try{const d=await api('auth');setUser(d.user);setSetup(d.setupRequired);setReady(true);}catch(e){setErr((e as Error).message)}}useEffect(()=>{refresh()},[]);
 async function login(e:any){e.preventDefault();setBusy(true);setErr('');const f=Object.fromEntries(new FormData(e.currentTarget));try{const d=await api(setup?'setup':invite?'accept-invite':'login',{...f,token:invite});history.replaceState(null,'','/');setUser(d.user);setSetup(false)}catch(e){setErr((e as Error).message)}finally{setBusy(false)}}
 if(!ready)return <div className="login-shell"><section className="login-card">{err||'جارٍ الاتصال بالبرنامج…'}{err&&<button onClick={refresh}>إعادة المحاولة</button>}</section></div>;
 if(!user)return <div className="login-shell"><section className="login-card"><div className="login-mark">✦</div><h1>الأيادي الخضراء</h1><p>حسابات وإدارة المشتل</p><h2>{setup?'إعداد حساب تامر':invite?'تفعيل حساب الشريك':'تسجيل الدخول'}</h2><form onSubmit={login}>{setup&&<><label className="field">رمز التهيئة<input name="setupKey" type="password" autoComplete="off" required/></label><label className="field">الاسم<input name="name" defaultValue="تامر" required/></label></>}{!invite&&<label className="field">اسم الدخول<input dir="ltr" name="username" autoComplete="username" defaultValue={setup?'tamer':''} required minLength={3} maxLength={40}/></label>}<label className="field">كلمة المرور<input dir="ltr" name="password" type="password" autoComplete={setup||invite?'new-password':'current-password'} minLength={setup||invite?12:1} maxLength={128} required/></label>{(setup||invite)&&<p className="subtle">اختَر كلمة مرور من 12 حرفاً على الأقل.</p>}{err&&<p className="error" role="alert">{err}</p>}<button className="primary" disabled={busy}>{busy?'جارٍ التحقق…':setup?'إنشاء الحساب':invite?'تفعيل الحساب':'دخول'}</button></form><small>تسجيل دخول خاص بالمشتل</small></section></div>;
 return <><div className="account-strip"><span>مرحباً، {user.name}</span><div><button onClick={async()=>{setManage(true);setErr('');setMsg('');if(user.role==='owner'){try{setUsers((await api('users')).users)}catch(e){setErr((e as Error).message)}}}}>حسابي {user.role==='owner'?'والمستخدمون':''}</button><button onClick={async()=>{try{await api('logout',{});setUser(null)}catch(e){setErr((e as Error).message)}}}>تسجيل الخروج</button></div></div><App/><Dialog open={manage} onOpenChange={setManage}><DialogContent dir="rtl" className="editor"><DialogHeader><DialogTitle>الحساب والدخول</DialogTitle><DialogDescription>أنت مسجل باسم {user.username}</DialogDescription></DialogHeader>{err&&<p className="error">{err}</p>}{msg&&<p className="notice">{msg}</p>}{user.role==='owner'&&<><h2>حساب فارس</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);setErr('');try{const f=Object.fromEntries(new FormData(e.currentTarget));const d=await api('invite',f);setLink(d.link)}catch(e){setErr((e as Error).message)}finally{setBusy(false)}}}><div className="form-grid"><label className="field">الاسم<input name="name" defaultValue="فارس ابو جاموس" required/></label><label className="field">اسم الدخول<input name="username" defaultValue="fares" required pattern="[a-zA-Z0-9._-]{3,40}"/></label></div><button className="primary" disabled={busy}>إنشاء رابط تفعيل لمدة 24 ساعة</button></form>{link&&<label className="field">انسخ الرابط وأرسله لفارس ليختار كلمة مروره<input readOnly value={link} dir="ltr" onFocus={e=>e.target.select()}/></label>}<p className="subtle">الشريك يستطيع تسجيل ومراجعة حسابات المشتل. إدارة حسابات الدخول متاحة لتامر فقط.</p>{users.map(u=><div className="balance-row" key={u.id}><span>{u.name} · {u.username}</span>{u.role==='partner'&&<button onClick={async()=>{if(!confirm('إلغاء دخول هذا المستخدم؟ تبقى حركاته المالية محفوظة.'))return;try{await api('revoke-user',{id:u.id});setUsers((await api('users')).users)}catch(e){setErr((e as Error).message)}}}>إلغاء الدخول</button>}</div>)}</>}<h2>تغيير كلمة المرور</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);setErr('');setMsg('');const form=e.currentTarget;try{await api('password',Object.fromEntries(new FormData(form)));form.reset();setMsg('تم تغيير كلمة المرور وإغلاق الجلسات الأخرى')}catch(e){setErr((e as Error).message)}finally{setBusy(false)}}}><label className="field">كلمة المرور الحالية<input name="current" type="password" autoComplete="current-password" required/></label><label className="field">كلمة المرور الجديدة<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><button className="primary" disabled={busy}>حفظ كلمة المرور</button></form></DialogContent></Dialog></>;
}
createRoot(document.getElementById('root')!).render(<Root/>);
