import assert from 'node:assert/strict';
import {initial,apply,balances} from '../lib/ledger.ts';
let s=initial();const go=a=>s=apply(s,a,'accounting-test');const tx=a=>go({action:'transaction',date:'2026-09-24',...a});
const product=(name,price)=>{go({action:'product',name,unit:'وحدة',price,min:0});return s.products.at(-1).id;};
const seed=product('بذور',20),out=product('شتلات منتجة',300);
tx({type:'capital',party:'1',amount:100000});
tx({type:'purchase',lines:[{product:seed,qty:1000,price:20}],paid:20000});
tx({type:'production_start',name:'دفعة 1',product:out,planned:1000,amount:10000,lines:[{product:seed,qty:1000}]});
let batch=s.batches[0].id;assert.equal(balances(s).wip,30000);assert.equal(balances(s).inventory,0);assert.equal(balances(s).cash,70000);
tx({type:'production_cost',batchId:batch,amount:10000,lines:[]});assert.equal(balances(s).wip,40000);
tx({type:'production_finish',batchId:batch,good:800});assert.equal(s.products.find(x=>x.id===out).qty,800);assert.equal(balances(s).inventory,40000);assert.equal(balances(s).wip,0);assert.equal(s.batches[0].cost/s.batches[0].good,50);
assert.throws(()=>tx({type:'production_cost',batchId:batch,amount:1,lines:[]}));
tx({type:'sale',lines:[{product:out,qty:100,price:300}],paid:30000});assert.equal(balances(s).cogs,5000);assert.equal(balances(s).inventory,35000);assert.equal(balances(s).cash,90000);
go({action:'reverse',id:s.transactions.at(-1).id,note:'عكس البيع'});assert.equal(balances(s).inventory,40000);
go({action:'reverse',id:s.transactions.filter(x=>!x.voided&&x.type!=='reversal').at(-1).id,note:'عكس إكمال الدفعة'});assert.equal(balances(s).wip,40000);assert.equal(s.batches[0].status,'growing');assert.equal(balances(s).inventory,0);
assert.throws(()=>tx({type:'production_finish',batchId:batch,good:1001}));
tx({type:'production_finish',batchId:batch,good:0});assert.equal(balances(s).waste,40000);assert.equal(balances(s).wip,0);assert.equal(balances(s).inventory,0);
assert.equal(Object.values(balances(s)).reduce((a,b)=>a+b,0),0);
// Credit and moving average remain correct alongside production.
go({action:'contact',name:'عميل',kind:'customer'});const c=s.contacts.at(-1).id;
go({action:'contact',name:'مورد',kind:'supplier'});const v=s.contacts.at(-1).id;
tx({type:'purchase',party:v,lines:[{product:out,qty:100,price:100}],paid:5000});
tx({type:'sale',party:c,lines:[{product:out,qty:20,price:300}],paid:2000});assert.equal(balances(s)['ar:'+c],4000);assert.equal(balances(s)['ap:'+v],-5000);
tx({type:'receipt',party:c,amount:4000});tx({type:'payment',party:v,amount:5000});assert.equal(balances(s)['ar:'+c],0);assert.equal(balances(s)['ap:'+v],0);
assert.throws(()=>tx({type:'sale',lines:[{product:out,qty:1000,price:300}],paid:0}));assert.throws(()=>tx({type:'receipt',party:c,amount:1}));
tx({type:'purchase',lines:[{product:out,qty:20,price:200}],paid:4000});assert.equal(s.products.find(x=>x.id===out).value,12000);
tx({type:'sale',lines:[{product:out,qty:100,price:300}],paid:30000});assert.equal(s.products.find(x=>x.id===out).value,0);
assert.equal(Object.values(balances(s)).reduce((a,b)=>a+b,0),0);assert.throws(()=>tx({type:'expense',note:'مصروف',amount:1e9}));
assert.throws(()=>tx({type:'capital',party:'1',amount:10,date:'2026-01-01'}));
console.log('PASS: production materials, WIP, extra costs, partial germination, completion, sale cost, reversal, total loss, credit settlements, weighted average, balanced journal, oversell and cash guards.');
